31.times do |n|
  user_count = n+126
  time = Time.now.to_i
  Like.create(
    user_id:user_count,
    item_id:99,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:100,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:101,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:102,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:103,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:104,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:105,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:106,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:107,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:108,
    TIMESTAMP:time,
  )
end
101.times do |n|
  user_count = n+100
  time = Time.now.to_i
  Like.create(
    user_id:user_count,
    item_id:109,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:110,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:111,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:112,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:113,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:114,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:115,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:116,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:117,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:118,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:119,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:120,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:121,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:122,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:123,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:124,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:125,
    TIMESTAMP:time,
  ) 
  Like.create(
    user_id:user_count,
    item_id:126,
    TIMESTAMP:time,
  ) 
  Like.create(
    user_id:user_count,
    item_id:127,
    TIMESTAMP:time,
  ) 
  Like.create(
    user_id:user_count,
    item_id:128,
    TIMESTAMP:time,
  ) 
end
101.times do |n|
  user_count = n+1
  time = Time.now.to_i
  Like.create(
    user_id:user_count,
    item_id:129,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:130,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:131,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:132,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:133,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:134,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:135,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:136,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:136,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:137,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:138,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:139,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:140,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:141,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:142,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:143,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:144,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:145,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:146,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:147,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:148,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:149,
    TIMESTAMP:time,
  )
end

81.times do |n|
  user_count = n+121
  time = Time.now.to_i
  Like.create(
    user_id:user_count,
    item_id:150,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:151,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:152,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:153,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:154,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:155,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:156,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:157,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:158,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:159,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:160,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:161,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:162,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:163,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:164,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:165,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:166,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:167,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:168,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:169,
    TIMESTAMP:time,
  )
end