151.times do |n|
  user_count = n
  time = Time.now.to_i
  Like.create(
    user_id:user_count,
    item_id:1,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:2,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:3,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:4,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:5,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:6,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:7,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:8,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:9,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:10,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:11,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:12,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:13,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:14,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:15,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:16,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:17,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:18,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:19,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:20,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:21,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:22,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:23,
    TIMESTAMP:time,
  )
end

101.times do |n|
  user_count = n+99
  time = Time.now.to_i
  Like.create(
    user_id:user_count,
    item_id:24,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:25,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:26,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:27,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:28,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:29,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:30,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:31,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:32,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:33,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:34,
    TIMESTAMP:time,
  )
end

26.times do |n|
  user_count = n+75
  time = Time.now.to_i
  Like.create(
    user_id:user_count,
    item_id:35,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:36,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:37,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:38,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:39,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:40,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:41,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:42,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:43,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:44,
    TIMESTAMP:time,
  )
end

31.times do |n|
  user_count = n+101
  time = Time.now.to_i
  Like.create(
    user_id:user_count,
    item_id:45,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:46,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:47,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:48,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:49,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:50,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:51,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:52,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:53,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:54,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:55,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:56,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:57,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:58,
    TIMESTAMP:time,
  )
end

21.times do |n|
  user_count = n+1
  time = Time.now.to_i
  Like.create(
    user_id:user_count,
    item_id:59,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:60,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:61,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:62,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:63,
    TIMESTAMP:time,
  )
end

51.times do |n|
  user_count = n+21
  time = Time.now.to_i
  Like.create(
    user_id:user_count,
    item_id:64,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:65,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:66,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:67,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:68,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:69,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:70,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:71,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:72,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:73,
    TIMESTAMP:time,
  )
end

26.times do |n|
  user_count = n+71
  time = Time.now.to_i
  Like.create(
    user_id:user_count,
    item_id:74,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:75,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:76,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:77,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:78,
    TIMESTAMP:time,
  )
end

31.times do |n|
  user_count = n+96
  time = Time.now.to_i
  Like.create(
    user_id:user_count,
    item_id:79,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:80,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:81,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:82,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:79,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:80,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:81,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:82,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:83,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:84,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:85,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:86,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:87,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:88,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:89,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:90,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:91,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:92,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:93,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:94,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:95,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:96,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:97,
    TIMESTAMP:time,
  )
  Like.create(
    user_id:user_count,
    item_id:98,
    TIMESTAMP:time,
  )
end