151.times do |n|
  user_count = n
  Like.create(
    user_id:user_count,
    item_id:1,
  )
  Like.create(
    user_id:user_count,
    item_id:2,
  )
  Like.create(
    user_id:user_count,
    item_id:3,
  )
  Like.create(
    user_id:user_count,
    item_id:4,
  )
  Like.create(
    user_id:user_count,
    item_id:5,
  )
  Like.create(
    user_id:user_count,
    item_id:6,
  )
  Like.create(
    user_id:user_count,
    item_id:7,
  )
  Like.create(
    user_id:user_count,
    item_id:8,
  )
  Like.create(
    user_id:user_count,
    item_id:9,
  )
  Like.create(
    user_id:user_count,
    item_id:10,
  )
  Like.create(
    user_id:user_count,
    item_id:11,
  )
  Like.create(
    user_id:user_count,
    item_id:12,
  )
  Like.create(
    user_id:user_count,
    item_id:13,
  )
  Like.create(
    user_id:user_count,
    item_id:14,
  )
  Like.create(
    user_id:user_count,
    item_id:15,
  )
  Like.create(
    user_id:user_count,
    item_id:16,
  )
  Like.create(
    user_id:user_count,
    item_id:17,
  )
  Like.create(
    user_id:user_count,
    item_id:18,
  )
  Like.create(
    user_id:user_count,
    item_id:19,
  )
  Like.create(
    user_id:user_count,
    item_id:20,
  )
  Like.create(
    user_id:user_count,
    item_id:21,
  )
  Like.create(
    user_id:user_count,
    item_id:22,
  )
  Like.create(
    user_id:user_count,
    item_id:23,
  )
end

101.times do |n|
  user_count = n+99
  Like.create(
    user_id:user_count,
    item_id:24,
  )
  Like.create(
    user_id:user_count,
    item_id:25,
  )
  Like.create(
    user_id:user_count,
    item_id:26,
  )
  Like.create(
    user_id:user_count,
    item_id:27,
  )
  Like.create(
    user_id:user_count,
    item_id:28,
  )
  Like.create(
    user_id:user_count,
    item_id:29,
  )
  Like.create(
    user_id:user_count,
    item_id:30,
  )
  Like.create(
    user_id:user_count,
    item_id:31,
  )
  Like.create(
    user_id:user_count,
    item_id:32,
  )
  Like.create(
    user_id:user_count,
    item_id:33,
  )
  Like.create(
    user_id:user_count,
    item_id:34,
  )
end

26.times do |n|
  user_count = n+75
  Like.create(
    user_id:user_count,
    item_id:35,
  )
  Like.create(
    user_id:user_count,
    item_id:36,
  )
  Like.create(
    user_id:user_count,
    item_id:37,
  )
  Like.create(
    user_id:user_count,
    item_id:38,
  )
  Like.create(
    user_id:user_count,
    item_id:39,
  )
  Like.create(
    user_id:user_count,
    item_id:40,
  )
  Like.create(
    user_id:user_count,
    item_id:41,
  )
  Like.create(
    user_id:user_count,
    item_id:42,
  )
  Like.create(
    user_id:user_count,
    item_id:43,
  )
  Like.create(
    user_id:user_count,
    item_id:44,
  )
end

31.times do |n|
  user_count = n+101
  Like.create(
    user_id:user_count,
    item_id:45,
  )
  Like.create(
    user_id:user_count,
    item_id:46,
  )
  Like.create(
    user_id:user_count,
    item_id:47,
  )
  Like.create(
    user_id:user_count,
    item_id:48,
  )
  Like.create(
    user_id:user_count,
    item_id:49,
  )
  Like.create(
    user_id:user_count,
    item_id:50,
  )
  Like.create(
    user_id:user_count,
    item_id:51,
  )
  Like.create(
    user_id:user_count,
    item_id:52,
  )
  Like.create(
    user_id:user_count,
    item_id:53,
  )
  Like.create(
    user_id:user_count,
    item_id:54,
  )
  Like.create(
    user_id:user_count,
    item_id:55,
  )
  Like.create(
    user_id:user_count,
    item_id:56,
  )
  Like.create(
    user_id:user_count,
    item_id:57,
  )
  Like.create(
    user_id:user_count,
    item_id:58,
  )
end

21.times do |n|
  user_count = n+1
  Like.create(
    user_id:user_count,
    item_id:59,
  )
  Like.create(
    user_id:user_count,
    item_id:60,
  )
  Like.create(
    user_id:user_count,
    item_id:61,
  )
  Like.create(
    user_id:user_count,
    item_id:62,
  )
  Like.create(
    user_id:user_count,
    item_id:63,
  )
end

51.times do |n|
  user_count = n+21
  Like.create(
    user_id:user_count,
    item_id:64,
  )
  Like.create(
    user_id:user_count,
    item_id:65,
  )
  Like.create(
    user_id:user_count,
    item_id:66,
  )
  Like.create(
    user_id:user_count,
    item_id:67,
  )
  Like.create(
    user_id:user_count,
    item_id:68,
  )
  Like.create(
    user_id:user_count,
    item_id:69,
  )
  Like.create(
    user_id:user_count,
    item_id:70,
  )
  Like.create(
    user_id:user_count,
    item_id:71,
  )
  Like.create(
    user_id:user_count,
    item_id:72,
  )
  Like.create(
    user_id:user_count,
    item_id:73,
  )
end

26.times do |n|
  user_count = n+71
  Like.create(
    user_id:user_count,
    item_id:74,
  )
  Like.create(
    user_id:user_count,
    item_id:75,
  )
  Like.create(
    user_id:user_count,
    item_id:76,
  )
  Like.create(
    user_id:user_count,
    item_id:77,
  )
  Like.create(
    user_id:user_count,
    item_id:78,
  )
end

31.times do |n|
  user_count = n+96
  Like.create(
    user_id:user_count,
    item_id:79,
  )
  Like.create(
    user_id:user_count,
    item_id:80,
  )
  Like.create(
    user_id:user_count,
    item_id:81,
  )
  Like.create(
    user_id:user_count,
    item_id:82,
  )
  Like.create(
    user_id:user_count,
    item_id:79,
  )
  Like.create(
    user_id:user_count,
    item_id:80,
  )
  Like.create(
    user_id:user_count,
    item_id:81,
  )
  Like.create(
    user_id:user_count,
    item_id:82,
  )
  Like.create(
    user_id:user_count,
    item_id:83,
  )
  Like.create(
    user_id:user_count,
    item_id:84,
  )
  Like.create(
    user_id:user_count,
    item_id:85,
  )
  Like.create(
    user_id:user_count,
    item_id:86,
  )
  Like.create(
    user_id:user_count,
    item_id:87,
  )
  Like.create(
    user_id:user_count,
    item_id:88,
  )
  Like.create(
    user_id:user_count,
    item_id:89,
  )
  Like.create(
    user_id:user_count,
    item_id:90,
  )
  Like.create(
    user_id:user_count,
    item_id:91,
  )
  Like.create(
    user_id:user_count,
    item_id:92,
  )
  Like.create(
    user_id:user_count,
    item_id:93,
  )
  Like.create(
    user_id:user_count,
    item_id:94,
  )
  Like.create(
    user_id:user_count,
    item_id:95,
  )
  Like.create(
    user_id:user_count,
    item_id:96,
  )
  Like.create(
    user_id:user_count,
    item_id:97,
  )
  Like.create(
    user_id:user_count,
    item_id:98,
  )
end
31.times do |n|
  user_count = n+126
  Like.create(
    user_id:user_count,
    item_id:99,
  )
  Like.create(
    user_id:user_count,
    item_id:100,
  )
  Like.create(
    user_id:user_count,
    item_id:101,
  )
  Like.create(
    user_id:user_count,
    item_id:102,
  )
  Like.create(
    user_id:user_count,
    item_id:103,
  )
  Like.create(
    user_id:user_count,
    item_id:104,
  )
  Like.create(
    user_id:user_count,
    item_id:105,
  )
  Like.create(
    user_id:user_count,
    item_id:106,
  )
  Like.create(
    user_id:user_count,
    item_id:107,
  )
  Like.create(
    user_id:user_count,
    item_id:108,
  )
end
101.times do |n|
  user_count = n+100
  Like.create(
    user_id:user_count,
    item_id:109,
  )
  Like.create(
    user_id:user_count,
    item_id:110,
  )
  Like.create(
    user_id:user_count,
    item_id:111,
  )
  Like.create(
    user_id:user_count,
    item_id:112,
  )
  Like.create(
    user_id:user_count,
    item_id:113,
  )
  Like.create(
    user_id:user_count,
    item_id:114,
  )
  Like.create(
    user_id:user_count,
    item_id:115,
  )
  Like.create(
    user_id:user_count,
    item_id:116,
  )
  Like.create(
    user_id:user_count,
    item_id:117,
  )
  Like.create(
    user_id:user_count,
    item_id:118,
  )
  Like.create(
    user_id:user_count,
    item_id:119,
  )
  Like.create(
    user_id:user_count,
    item_id:120,
  )
  Like.create(
    user_id:user_count,
    item_id:121,
  )
  Like.create(
    user_id:user_count,
    item_id:122,
  )
  Like.create(
    user_id:user_count,
    item_id:123,
  )
  Like.create(
    user_id:user_count,
    item_id:124,
  )
  Like.create(
    user_id:user_count,
    item_id:125,
  ) 
  Like.create(
    user_id:user_count,
    item_id:126,
  ) 
  Like.create(
    user_id:user_count,
    item_id:127,
  ) 
  Like.create(
    user_id:user_count,
    item_id:128,
  ) 
end
101.times do |n|
  user_count = n+1
  Like.create(
    user_id:user_count,
    item_id:129,
  )
  Like.create(
    user_id:user_count,
    item_id:130,
  )
  Like.create(
    user_id:user_count,
    item_id:131,
  )
  Like.create(
    user_id:user_count,
    item_id:132,
  )
  Like.create(
    user_id:user_count,
    item_id:133,
  )
  Like.create(
    user_id:user_count,
    item_id:134,
  )
  Like.create(
    user_id:user_count,
    item_id:135,
  )
  Like.create(
    user_id:user_count,
    item_id:136,
  )
  Like.create(
    user_id:user_count,
    item_id:136,
  )
  Like.create(
    user_id:user_count,
    item_id:137,
  )
  Like.create(
    user_id:user_count,
    item_id:138,
  )
  Like.create(
    user_id:user_count,
    item_id:139,
  )
  Like.create(
    user_id:user_count,
    item_id:140,
  )
  Like.create(
    user_id:user_count,
    item_id:141,
  )
  Like.create(
    user_id:user_count,
    item_id:142,
  )
  Like.create(
    user_id:user_count,
    item_id:143,
  )
  Like.create(
    user_id:user_count,
    item_id:144,
  )
  Like.create(
    user_id:user_count,
    item_id:145,
  )
  Like.create(
    user_id:user_count,
    item_id:146,
  )
  Like.create(
    user_id:user_count,
    item_id:147,
  )
  Like.create(
    user_id:user_count,
    item_id:148,
  )
  Like.create(
    user_id:user_count,
    item_id:149,
  )
end

81.times do |n|
  user_count = n+121
  Like.create(
    user_id:user_count,
    item_id:150,
  )
  Like.create(
    user_id:user_count,
    item_id:151,
  )
  Like.create(
    user_id:user_count,
    item_id:152,
  )
  Like.create(
    user_id:user_count,
    item_id:153,
  )
  Like.create(
    user_id:user_count,
    item_id:154,
  )
  Like.create(
    user_id:user_count,
    item_id:155,
  )
  Like.create(
    user_id:user_count,
    item_id:156,
  )
  Like.create(
    user_id:user_count,
    item_id:157,
  )
  Like.create(
    user_id:user_count,
    item_id:158,
  )
  Like.create(
    user_id:user_count,
    item_id:159,
  )
  Like.create(
    user_id:user_count,
    item_id:160,
  )
  Like.create(
    user_id:user_count,
    item_id:161,
  )
  Like.create(
    user_id:user_count,
    item_id:162,
  )
  Like.create(
    user_id:user_count,
    item_id:163,
  )
  Like.create(
    user_id:user_count,
    item_id:164,
  )
  Like.create(
    user_id:user_count,
    item_id:165,
  )
  Like.create(
    user_id:user_count,
    item_id:166,
  )
  Like.create(
    user_id:user_count,
    item_id:167,
  )
  Like.create(
    user_id:user_count,
    item_id:168,
  )
  Like.create(
    user_id:user_count,
    item_id:169,
  )
end